[GLOBAL]
pants_version = "2.15.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[anonymous-telemetry]
enabled = true
repo_id = "9a0568c1-c694-43f2-a9f9-b20efbb65174"

[pex-cli]
version = "v2.1.115"
url_template = "https://github.com/ento/pex/releases/download/{version}/pex"
known_versions = [
  "v2.1.115|linux_x86_64|26da5510ef063e62945bc24ecc68833e8de1035dc5e70d8edd1c2931ae539eae|4098477",
]

[python]
interpreter_constraints = [">=3.8,<4"]
enable_resolves = true

[python-bootstrap]
# Limit to Python interpreter installed by flake.nix
search_path = ["%(env.PYTHON_SEARCH_PATH)s"]

[pytest]
lockfile = "3rdparty/python/pytest.lock"
extra_requirements.add = [
  "pytest-freezer",
  "syrupy",
]

[test]
extra_env_vars = [
  # FIXME https://github.com/pantsbuild/pants/issues/11622, see tests/conftest.py and scripts/pants-with-snapshot-sandbox.sh
  "PANTS_WITH_SNAPSHOTS_HACK_DIR",
]
