[GLOBAL]
pants_version = "2.15.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[python]
interpreter_constraints = [">=3.8,<4"]
enable_resolves = true

[pytest]
lockfile = "3rdparty/python/pytest.lock"
extra_requirements.add = [
  "pytest-freezer"
]
