[GLOBAL]
pants_version = "2.15.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[python]
interpreter_constraints = [">=3.8,<4"]
enable_resolves = true

[python-bootstrap]
# Limit to Python interpreter installed by flake.nix
search_path = ["%(env.PYTHON_SEARCH_PATH)s"]

[pytest]
lockfile = "3rdparty/python/pytest.lock"
extra_requirements.add = [
  "pytest-freezer",
  "syrupy",
]

[test]
extra_env_vars = [
  # FIXME https://github.com/pantsbuild/pants/issues/11622, see tests/conftest.py and scripts/pants-with-snapshot-sandbox.sh
  "PANTS_WITH_SNAPSHOTS_HACK_DIR",
]
