[GLOBAL]
pants_version = "2.21.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[anonymous-telemetry]
enabled = true
repo_id = "9a0568c1-c694-43f2-a9f9-b20efbb65174"

[python]
interpreter_constraints = [">=3.8.1,<4"]
pip_version = "latest"
enable_resolves = true

[python.resolves]
python-default = "3rdparty/python/default.lock"
black = "3rdparty/python/black.lock"
flake8 = "3rdparty/python/flake8.lock"

[python-bootstrap]
# Limit to Python interpreter installed by flake.nix
search_path = ["%(env.PYTHON_SEARCH_PATH)s"]

[black]
install_from_resolve = "black"

[flake8]
install_from_resolve = "flake8"

[pytest]
install_from_resolve = "python-default"

[test]
extra_env_vars = [
  # FIXME https://github.com/pantsbuild/pants/issues/11622, see tests/conftest.py and scripts/pants-with-snapshot-sandbox.sh
  "PANTS_WITH_SNAPSHOTS_HACK_DIR",
]
use_coverage = true

[coverage-py]
report = ["console", "html"]
filter = ["src/tinyalert"]
