[tool.isort]
profile = "black"

[tool.poetry]
name = "tinyalert"
version = "0.1.0"
description = ""
authors = ["ento"]
license = "MIT"
readme = "README.md"
packages = [
  { include = "tinyalert", from = "src" },
]

[tool.poetry.scripts]
tinyalerts = 'tinyalert.cli:cli'

[tool.poetry.dependencies]
python = "^3.8.16"
click = "^8.1.3"
termcolor = "^2.2.0"
tabulate = "^0.9.0"
sparklines = "^0.4.2"
pydantic = {version = "^2.0a3", allow-prereleases = true}
tomli = "^2.0.1"
sqlalchemy = "^2.0.11"
alembic = "^1.10.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
tomli-w = "^1.0.0"
pytest-freezer = "^0.4.6"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
