"""Add generation column

Revision ID: 3eb91cd00239
Revises: 9cb828bece2f
Create Date: 2023-08-16 20:40:08.190527

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3eb91cd00239"
down_revision = "9cb828bece2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column("generation", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "generation")
    # ### end Alembic commands ###
