"""Add epoch column

Revision ID: 9cb828bece2f
Revises: 2e32d886a3b7
Create Date: 2023-05-20 16:52:54.289363

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9cb828bece2f"
down_revision = "2e32d886a3b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points", sa.Column("epoch", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "epoch")
    # ### end Alembic commands ###
