"""Add tags column

Revision ID: a89fc25c0947
Revises: 3eb91cd00239
Create Date: 2023-09-11 22:01:34.382935

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a89fc25c0947"
down_revision = "3eb91cd00239"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points", sa.Column("tags", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "tags")
    # ### end Alembic commands ###
