"""Initial

Revision ID: cabfb49f9f42
Revises: 
Create Date: 2023-05-02 01:16:29.957045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cabfb49f9f42"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("absolute_max", sa.Float(), nullable=True),
        sa.Column("absolute_min", sa.Float(), nullable=True),
        sa.Column("relative_max", sa.Float(), nullable=True),
        sa.Column("relative_min", sa.Float(), nullable=True),
        sa.Column(
            "ignore", sa.Enum("relative", "all_", name="ignoretype"), nullable=True
        ),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("diffable_content", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("points")
    # ### end Alembic commands ###
