on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  PYTHON_SEARCH_PATH: "<PATH>"

jobs:
  install-and-use:
    runs-on: ubuntu-20.04
    steps:
      - name: debug
        run: |
          umask -S
